// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserTelemetryRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTelemetryRequest) Reset()         { *m = UserTelemetryRequest{} }
func (m *UserTelemetryRequest) String() string { return proto.CompactTextString(m) }
func (*UserTelemetryRequest) ProtoMessage()    {}
func (*UserTelemetryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{0}
}

func (m *UserTelemetryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTelemetryRequest.Unmarshal(m, b)
}
func (m *UserTelemetryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTelemetryRequest.Marshal(b, m, deterministic)
}
func (m *UserTelemetryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTelemetryRequest.Merge(m, src)
}
func (m *UserTelemetryRequest) XXX_Size() int {
	return xxx_messageInfo_UserTelemetryRequest.Size(m)
}
func (m *UserTelemetryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTelemetryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserTelemetryRequest proto.InternalMessageInfo

func (m *UserTelemetryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserTelemetryResponse struct {
	Telemetries          []*Telemetry `protobuf:"bytes,1,rep,name=telemetries,proto3" json:"telemetries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserTelemetryResponse) Reset()         { *m = UserTelemetryResponse{} }
func (m *UserTelemetryResponse) String() string { return proto.CompactTextString(m) }
func (*UserTelemetryResponse) ProtoMessage()    {}
func (*UserTelemetryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{1}
}

func (m *UserTelemetryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTelemetryResponse.Unmarshal(m, b)
}
func (m *UserTelemetryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTelemetryResponse.Marshal(b, m, deterministic)
}
func (m *UserTelemetryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTelemetryResponse.Merge(m, src)
}
func (m *UserTelemetryResponse) XXX_Size() int {
	return xxx_messageInfo_UserTelemetryResponse.Size(m)
}
func (m *UserTelemetryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTelemetryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTelemetryResponse proto.InternalMessageInfo

func (m *UserTelemetryResponse) GetTelemetries() []*Telemetry {
	if m != nil {
		return m.Telemetries
	}
	return nil
}

type TelemetryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryResponse) Reset()         { *m = TelemetryResponse{} }
func (m *TelemetryResponse) String() string { return proto.CompactTextString(m) }
func (*TelemetryResponse) ProtoMessage()    {}
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{2}
}

func (m *TelemetryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryResponse.Unmarshal(m, b)
}
func (m *TelemetryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryResponse.Marshal(b, m, deterministic)
}
func (m *TelemetryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryResponse.Merge(m, src)
}
func (m *TelemetryResponse) XXX_Size() int {
	return xxx_messageInfo_TelemetryResponse.Size(m)
}
func (m *TelemetryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryResponse proto.InternalMessageInfo

type Telemetry struct {
	Timestamp            int64          `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId               string         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gps                  *GPS           `protobuf:"bytes,3,opt,name=gps,proto3" json:"gps,omitempty"`
	Accelerometer        *Accelerometer `protobuf:"bytes,4,opt,name=accelerometer,proto3" json:"accelerometer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{3}
}

func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (m *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(m, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

func (m *Telemetry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Telemetry) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Telemetry) GetGps() *GPS {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *Telemetry) GetAccelerometer() *Accelerometer {
	if m != nil {
		return m.Accelerometer
	}
	return nil
}

type GPS struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed                float64  `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	ConnectedSatellites  int64    `protobuf:"varint,5,opt,name=connected_satellites,json=connectedSatellites,proto3" json:"connected_satellites,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPS) Reset()         { *m = GPS{} }
func (m *GPS) String() string { return proto.CompactTextString(m) }
func (*GPS) ProtoMessage()    {}
func (*GPS) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{4}
}

func (m *GPS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPS.Unmarshal(m, b)
}
func (m *GPS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPS.Marshal(b, m, deterministic)
}
func (m *GPS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPS.Merge(m, src)
}
func (m *GPS) XXX_Size() int {
	return xxx_messageInfo_GPS.Size(m)
}
func (m *GPS) XXX_DiscardUnknown() {
	xxx_messageInfo_GPS.DiscardUnknown(m)
}

var xxx_messageInfo_GPS proto.InternalMessageInfo

func (m *GPS) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GPS) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GPS) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *GPS) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *GPS) GetConnectedSatellites() int64 {
	if m != nil {
		return m.ConnectedSatellites
	}
	return 0
}

type Accelerometer struct {
	AngleX               float64  `protobuf:"fixed64,1,opt,name=angle_x,json=angleX,proto3" json:"angle_x,omitempty"`
	AngleY               float64  `protobuf:"fixed64,2,opt,name=angle_y,json=angleY,proto3" json:"angle_y,omitempty"`
	AngleZ               float64  `protobuf:"fixed64,3,opt,name=angle_z,json=angleZ,proto3" json:"angle_z,omitempty"`
	GForce               float64  `protobuf:"fixed64,4,opt,name=g_force,json=gForce,proto3" json:"g_force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accelerometer) Reset()         { *m = Accelerometer{} }
func (m *Accelerometer) String() string { return proto.CompactTextString(m) }
func (*Accelerometer) ProtoMessage()    {}
func (*Accelerometer) Descriptor() ([]byte, []int) {
	return fileDescriptor_edbfcf76559f568d, []int{5}
}

func (m *Accelerometer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accelerometer.Unmarshal(m, b)
}
func (m *Accelerometer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accelerometer.Marshal(b, m, deterministic)
}
func (m *Accelerometer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accelerometer.Merge(m, src)
}
func (m *Accelerometer) XXX_Size() int {
	return xxx_messageInfo_Accelerometer.Size(m)
}
func (m *Accelerometer) XXX_DiscardUnknown() {
	xxx_messageInfo_Accelerometer.DiscardUnknown(m)
}

var xxx_messageInfo_Accelerometer proto.InternalMessageInfo

func (m *Accelerometer) GetAngleX() float64 {
	if m != nil {
		return m.AngleX
	}
	return 0
}

func (m *Accelerometer) GetAngleY() float64 {
	if m != nil {
		return m.AngleY
	}
	return 0
}

func (m *Accelerometer) GetAngleZ() float64 {
	if m != nil {
		return m.AngleZ
	}
	return 0
}

func (m *Accelerometer) GetGForce() float64 {
	if m != nil {
		return m.GForce
	}
	return 0
}

func init() {
	proto.RegisterType((*UserTelemetryRequest)(nil), "UserTelemetryRequest")
	proto.RegisterType((*UserTelemetryResponse)(nil), "UserTelemetryResponse")
	proto.RegisterType((*TelemetryResponse)(nil), "TelemetryResponse")
	proto.RegisterType((*Telemetry)(nil), "Telemetry")
	proto.RegisterType((*GPS)(nil), "GPS")
	proto.RegisterType((*Accelerometer)(nil), "Accelerometer")
}

func init() { proto.RegisterFile("telemetry.proto", fileDescriptor_edbfcf76559f568d) }

var fileDescriptor_edbfcf76559f568d = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xe5, 0x75, 0x2b, 0xf4, 0x55, 0x85, 0xe1, 0x75, 0x23, 0xaa, 0x38, 0x54, 0x39, 0xf5,
	0x00, 0x89, 0x56, 0x76, 0x43, 0x42, 0x0c, 0x09, 0x2a, 0x6e, 0x93, 0x03, 0x12, 0xec, 0x52, 0xb9,
	0xce, 0x23, 0x18, 0x92, 0x38, 0xd8, 0xaf, 0x13, 0xe3, 0x0f, 0xe0, 0xcc, 0x5f, 0xc1, 0xdf, 0x89,
	0xe2, 0x76, 0x49, 0xba, 0xed, 0x12, 0xe9, 0xfb, 0xbe, 0x67, 0xeb, 0x17, 0xfb, 0x33, 0x3c, 0x26,
	0xcc, 0xb1, 0x40, 0xb2, 0xd7, 0x51, 0x65, 0x0d, 0x99, 0x30, 0x86, 0xf1, 0x27, 0x87, 0xf6, 0xe3,
	0x8d, 0x2d, 0xf0, 0xe7, 0x1a, 0x1d, 0xf1, 0xa7, 0xf0, 0x60, 0xed, 0xd0, 0x2e, 0x75, 0x1a, 0xb0,
	0x29, 0x9b, 0x0d, 0x44, 0xbf, 0x96, 0x1f, 0xd2, 0xf0, 0x1d, 0x1c, 0xdf, 0x5a, 0xe0, 0x2a, 0x53,
	0x3a, 0xe4, 0xcf, 0x61, 0x78, 0xb3, 0xb9, 0x46, 0x17, 0xb0, 0x69, 0x6f, 0x36, 0x9c, 0x43, 0xd4,
	0x0e, 0x76, 0xe3, 0xf0, 0x08, 0x9e, 0xdc, 0xd9, 0x22, 0xfc, 0xcb, 0x60, 0xd0, 0xb8, 0xfc, 0x19,
	0x0c, 0x48, 0x17, 0xe8, 0x48, 0x16, 0x95, 0x87, 0xe8, 0x89, 0xd6, 0xe8, 0x02, 0xee, 0x75, 0x01,
	0xf9, 0x09, 0xf4, 0xb2, 0xca, 0x05, 0xbd, 0x29, 0x9b, 0x0d, 0xe7, 0xfb, 0xd1, 0xe2, 0x22, 0x11,
	0xb5, 0xc1, 0xcf, 0x60, 0x24, 0x95, 0xc2, 0x1c, 0xad, 0x29, 0x90, 0xd0, 0x06, 0xfb, 0x7e, 0xe2,
	0x51, 0x74, 0xde, 0x75, 0xc5, 0xee, 0x50, 0xf8, 0x8f, 0x41, 0x6f, 0x71, 0x91, 0xf0, 0x09, 0x3c,
	0xcc, 0x25, 0x69, 0x5a, 0xa7, 0xe8, 0x59, 0x98, 0x68, 0x74, 0x0d, 0x9a, 0x9b, 0x32, 0xdb, 0x84,
	0x7b, 0x3e, 0x6c, 0x0d, 0x3e, 0x86, 0x03, 0x57, 0x21, 0xa6, 0x9e, 0x88, 0x89, 0x8d, 0xa8, 0xd7,
	0xa4, 0xda, 0xa2, 0x22, 0x6d, 0x4a, 0x4f, 0x32, 0x10, 0xad, 0xc1, 0x4f, 0x61, 0xac, 0x4c, 0x59,
	0xa2, 0x22, 0x4c, 0x97, 0x4e, 0x12, 0xe6, 0xb9, 0x26, 0x74, 0xc1, 0x81, 0x3f, 0x85, 0xa3, 0x26,
	0x4b, 0x9a, 0x28, 0x74, 0x30, 0xda, 0xf9, 0x91, 0xfa, 0x80, 0x64, 0x99, 0xe5, 0xb8, 0xfc, 0xb5,
	0x05, 0xee, 0x7b, 0xf9, 0xb9, 0x0d, 0xae, 0xb7, 0xb0, 0x9b, 0xe0, 0x4b, 0x1b, 0xfc, 0xde, 0xb2,
	0x6e, 0x82, 0xcb, 0x3a, 0xc8, 0x96, 0x5f, 0x8d, 0x55, 0xe8, 0x51, 0x99, 0xe8, 0x67, 0xef, 0x6b,
	0x35, 0xff, 0xc3, 0xe0, 0xb0, 0xb9, 0xb0, 0x04, 0xed, 0x95, 0x56, 0xc8, 0x63, 0x18, 0x25, 0xf2,
	0x0a, 0xdb, 0x8b, 0xec, 0x94, 0x60, 0xc2, 0xa3, 0xbb, 0xcd, 0x39, 0x87, 0xc3, 0x05, 0xd2, 0x4e,
	0xab, 0xf8, 0x71, 0x74, 0x5f, 0x2d, 0x27, 0x27, 0xd1, 0xbd, 0xe5, 0x7b, 0xfb, 0xe6, 0xf2, 0x75,
	0xa6, 0xe9, 0xdb, 0x7a, 0x15, 0x29, 0x53, 0xc4, 0xea, 0xbb, 0x49, 0xad, 0x3c, 0x3d, 0x8b, 0x9b,
	0xb6, 0xbf, 0xd0, 0x86, 0xe2, 0x95, 0x54, 0x3f, 0xb0, 0x4c, 0x63, 0x59, 0xe9, 0x58, 0xe5, 0x1a,
	0x4b, 0x8a, 0x33, 0x5b, 0xa9, 0x57, 0xf5, 0x67, 0xd5, 0xf7, 0xef, 0xe1, 0xe5, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x55, 0x97, 0x83, 0x20, 0x22, 0x03, 0x00, 0x00,
}
